# permissions for end users to view challenges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: challenge-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-ctf
    app.kubernetes.io/part-of: k8s-ctf
    app.kubernetes.io/managed-by: kustomize
  name: challenge-viewer-role
rules:
- apiGroups:
  - ctf.thegoose.work
  resources:
  - challenges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ctf.thegoose.work
  resources:
  - challenges/status
  verbs:
  - get
