# permissions for end users to view privatechallenges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: privatechallenge-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-ctf
    app.kubernetes.io/part-of: k8s-ctf
    app.kubernetes.io/managed-by: kustomize
  name: privatechallenge-viewer-role
rules:
- apiGroups:
  - ctf.thegoose.work
  resources:
  - privatechallenges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ctf.thegoose.work
  resources:
  - privatechallenges/status
  verbs:
  - get
